### ISSUE TITLE
Code Lou Courses to be Completed

### ISSUE THREAD

**Issue by khots06** [khots06/Treehouse#2]
## TODO

*Courses left to complete Code Lou*

* [ ] Debugging CSS with Chrome DevTools
* [ ] Responsive Layouts
* [ ] Practice Media Queries
* [ ] CSS Flexbox Layout

🎉  🙆🏾‍♂️ 🎊
